<%@ include file="common/header.jspf"%>
<%@ include file="common/navigation.jspf"%>

		
	<div id="container">
		<div id="content">
			<h3>SETTINGS - UNDER CONSTRUCTION</h3> 
			<br>
			<h4>ToDo List:</h4>
			<ul>
				<li>Validation</li>
				<li>Full Javadoc implementation</li>
				<li>User access levels regulation</li>
				<li>Update/Delete links into buttons</li>
			</ul>
			<br><br><br><br>
			<div id="headersmall">
				<h4><label>Change Log:</label></h4>
			</div>
			<br>	

			<label>19.04.</label>
			<ul>
				<li>Removed annotations autogenerated ID from entity SEX but left BIGSERIAL definition in SQL</li>
				<li>CRUD with Contact-Sex relation works 100%. <a href="https://www.javainterviewpoint.com/spring-mvc-radiobutton-radiobuttons-example/">Radiobuttons</a> implementation planned.</li>
				<li>About and Settings pages refreshed.. quite a waste of time.</li>
				<li>Implemented ADDRESS entity. Functional 99% - update address adds new address entry, instead of updating the original one. Try out cascade options.</li>
				<li>Implemented all entities.Listing works, add form only loads, saving not implemented. Updating? Don't even wanna know..
			</ul>
			
			
		</div>
	</div>



<%@ include file="common/footer.jspf"%>